-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.products
(
    product_id integer NOT NULL,
    product_name character varying(50) NOT NULL,
    quantity_per_unit character varying(35) NOT NULL,
    unit_price double precision NOT NULL,
    discontinued boolean NOT NULL,
    category_name character varying(20) NOT NULL,
    description character varying(80) NOT NULL,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    employee_id integer NOT NULL,
    employee_name character varying(20) NOT NULL,
    title character varying(25) NOT NULL,
    city character varying(15) NOT NULL,
    country character varying(5) NOT NULL,
    reports_to integer,
    PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS public.order_details
(
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    unit_price double precision NOT NULL,
    quantity integer NOT NULL,
    discount double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id integer NOT NULL,
    customer_id character varying(5) NOT NULL,
    employee_id integer NOT NULL,
    order_date date NOT NULL,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id character varying(5) NOT NULL,
    company_name character varying(50) NOT NULL,
    contact_name character varying(30) NOT NULL,
    contact_title character varying(35) NOT NULL,
    city character varying(20) NOT NULL,
    country character varying(15) NOT NULL,
    PRIMARY KEY (customer_id)
);

ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT "order_id FK" FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT "product_id FK" FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT "customer_id FK" FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT "employee_id FK" FOREIGN KEY (employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;